version: '2'

services:
  mongo:
    image: mongo
    ports:
    - 27017:27017
    volumes:
    - ./mongodb:/data/db
  adminmongo:
    image: mrvautin/adminmongo
    environment:
      - HOST=0.0.0.0
    ports:
      - 1234:1234
    depends_on:
      - mongo